union Aux =
    AuxAnime
  | AuxAnimeFilm
  | AuxManga
  | AuxBook
  | AuxShortStory
  | AuxFilm
  | AuxTV
  | AuxAlbum
  | AuxGame

type AuxAnime {
  composers: [String!]
  directors: [String!]
  studios: [String!]
  writers: [String!]
}

type AuxAnimeFilm {
  composers: [String!]
  directors: [String!]
  studios: [String!]
  writers: [String!]
}

type AuxManga {
  artists: [String!]
  authors: [String!]
}

type AuxBook {
  authors: [String!]
}

type AuxShortStory {
  authors: [String!]
}

type AuxFilm {
  cinematographers: [String!]
  composers: [String!]
  directors: [String!]
  editors: [String!]
  writers: [String!]
}

type AuxTV {
  cinematographers: [String!]
  creators: [String!]
  composers: [String!]
  editors: [String!]
  writers: [String!]
}

type AuxAlbum {
  studios: [String!]
  composers: [String!]
  labels: [String!]
  producers: [String!]
}

type AuxGame {
  artists: [String!]
  composers: [String!]
  designers: [String!]
  developers: [String!]
  directors: [String!]
  programmers: [String!]
  writers: [String!]
}
