directive @goField(
	forceResolver: Boolean
	name: String
  omittable: Boolean
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION

enum APIType {
  API_NONE

  API_TRUFFLE
  API_MAL
  API_KITSU
  API_STEAM
  API_SPOTIFY
}

enum CorpusType {
  CORPUS_NONE

  CORPUS_ANIME
  CORPUS_ANIME_FILM
  CORPUS_MANGA
  CORPUS_BOOK
  CORPUS_SHORT_STORY
  CORPUS_FILM
  CORPUS_TV
  CORPUS_ALBUM
  CORPUS_GAME
}

enum ProviderType {
  PROVIDER_NONE
  PROVIDER_OTHER

  PROVIDER_CRUNCHYROLL
  PROVIDER_DISNEY_PLUS
  PROVIDER_HULU
  PROVIDER_HBO_MAX
  PROVIDER_NETFLIX
  PROVIDER_AMAZON_STREAMING
  PROVIDER_GOOGLE_PLAY
  PROVIDER_APPLE_TV
  PROVIDER_STEAM
}

type Title {
  language: String!
  title: String!
}

type Entry {
  id: ID!
  metadata: Metadata!
  corpus: CorpusType!
  queued: Boolean!
}

type Metadata {
  truffle: APIData!  # ID is the same as the Entry ID

  sources: [APIData!] @goField(forceResolver: true)
}

type APIData {
  api: APIType!
  id: ID!
  cached: Boolean!
  titles: [Title!]
  score: Float
  providers: [ProviderType!]
  aux: Aux
  tags: [String!]
}
