package model

var (
	DefaultConfig = &Config{
		MAL: &ConfigMAL{
			// ClientID is the publically-known MAL API, per
			// https://github.com/SuperMarcus/myanimelist-api-specification#requests.
			//
			// This API key may also be generated by creating an
			// account and requesting developer access.
			ClientID: "6114d00ca681b7701d1e15fe11a4987e",

			PopularityCutoff: 1500,
			SearchMaxResults: 50,
		},
	}
)

type ConfigMAL struct {
	ClientID         string
	PopularityCutoff int
	SearchMaxResults int
}

type Config struct {
	MAL *ConfigMAL
}
