package mal

import (
	"net/http"

	"github.com/nstratos/go-myanimelist/mal"
)

const (
	// clientID is the publically-known MAL API, per
	// https://github.com/SuperMarcus/myanimelist-api-specification#requests.
	//
	// This API key may also be generated by creating an account and
	// requesting developer access.
	clientID = "6114d00ca681b7701d1e15fe11a4987e"
)

type C struct {
	mal *mal.Client
}

func New() *C {
	return &C{
		mal: mal.NewClient(
			&http.Client{
				Transport: t{clientID: clientID},
			},
		),
	}
}

type t struct {
	clientID string
}

func (t t) RoundTrip(req *http.Request) (*http.Response, error) {
	req.Header.Add("X-MAL-CLIENT-ID", t.clientID)
	return http.DefaultTransport.RoundTrip(req)
}
