package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"context"
	"fmt"

	graph "github.com/minkezhang/truffle/api/graphql/generated"
	"github.com/minkezhang/truffle/api/graphql/generated/model"
)

// MutateEntry is the resolver for the MutateEntry field.
func (r *mutationResolver) MutateEntry(ctx context.Context, input *model.MutateEntryInput) (*model.MutateEntryOutput, error) {
	panic(fmt.Errorf("not implemented: MutateEntry - MutateEntry"))
}

// QueryEntry is the resolver for the QueryEntry field.
func (r *queryResolver) QueryEntry(ctx context.Context, input *model.QueryEntryInput) (*model.QueryEntryOutput, error) {
	panic(fmt.Errorf("not implemented: QueryEntry - QueryEntry"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
