package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"context"

	graph "github.com/minkezhang/truffle/api/graphql"
	"github.com/minkezhang/truffle/api/graphql/model"
)

// Sources is the resolver for the sources field.
func (r *metadataResolver) Sources(ctx context.Context, obj *model.Metadata) ([]*model.APIData, error) {
	// TODO(minkezhang): Query for sources if data is not cached.
	return obj.Sources, nil
}

// Metadata returns graph.MetadataResolver implementation.
func (r *Resolver) Metadata() graph.MetadataResolver { return &metadataResolver{r} }

type metadataResolver struct{ *Resolver }
