package mal

import (
	"net/http"

	"github.com/minkezhang/truffle/client"
)

const (
	// CLIENT_ID is the publically-known MAL API, per
	// https://github.com/SuperMarcus/myanimelist-api-specification#requests.
	//
	// This API key may also be generated by creating an
	// account and requesting developer access.
	CLIENT_ID = "6114d00ca681b7701d1e15fe11a4987e"
)

type O struct {
	transport http.RoundTripper
	auth      client.AuthType
}

func WithPublicAPIKey() O {
	return O{
		transport: t{
			cid: CLIENT_ID,
		},
		auth: client.AuthTypePublic,
	}
}

type t struct {
	cid string
}

func (t t) RoundTrip(req *http.Request) (*http.Response, error) {
	req.Header.Add("X-MAL-CLIENT-ID", t.cid)
	return http.DefaultTransport.RoundTrip(req)
}
