package mal

import (
	"net/http"
)

const (
	// CLIENT_ID is the publically-known MAL API, per
	// https://github.com/SuperMarcus/myanimelist-api-specification#requests.
	//
	// This API key may also be generated by creating an
	// account and requesting developer access.
	CLIENT_ID = "6114d00ca681b7701d1e15fe11a4987e"
)

type O struct {
	ClientID string
}

type transport struct {
	ClientID string
}

func (t transport) RoundTrip(req *http.Request) (*http.Response, error) {
	req.Header.Add("X-MAL-CLIENT-ID", t.ClientID)
	return http.DefaultTransport.RoundTrip(req)
}
