fragment APIDataParts on APIData {
  api
  id
  corpus
  titles {
    title
  }
  providers
  tags
  aux {
    ... on AuxAnime {
      studios
    }
    ... on AuxManga {
      authors
      artists
    }
  }
  tracker {
    ... on TrackerAnime {
      season
      episode
      last_updated
    }
    ... on TrackerManga {
      volume
      chapter
      last_updated
    }
  }
}
