scalar Time

union Tracker =
    TrackerAnime
  | TrackerManga
  | TrackerTV
  | TrackerBook

type TrackerAnime {
  season: String
  episode: String
  last_updated: Time
}

type TrackerTV {
  season: String
  episode: String
  last_updated: Time
}

type TrackerManga {
  volume: String
  chapter: String
  last_updated: Time
}

# Modern books are not typically serialized by the chapter and therefore do not
# require chapter markers. Physical and virtual bookmarks exist for this
# purpose.
type TrackerBook {
  volume: String
  last_updated: Time
}
