name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build github.com/minkezhang/truffle
      run: go build -v github.com/minkezhang/truffle/...

    - name: Vet github.com/minkezhang/truffle
      run: go vet -v github.com/minkezhang/truffle/...

    - name: Test github.com/minkezhang/truffle
      run: go test -v github.com/minkezhang/truffle/... -bench . -benchmem
