// database.proto
// Fully specifies the database spec.
//
// To generate this protobuf file, run
//   protoc -I api/ \
//     --go_out=api/ \
//     --go_opt=paths=import \
//     --go_opt=module=github.com/minkezhang/truffle/api \
//     api/*proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: api/config.proto

package config

import (
	_ "github.com/minkezhang/truffle/api/go/database"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mal *MALConfig `protobuf:"bytes,1,opt,name=mal,proto3" json:"mal,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_api_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetMal() *MALConfig {
	if x != nil {
		return x.Mal
	}
	return nil
}

type MALConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId         string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	PopularityCutoff int32  `protobuf:"varint,2,opt,name=popularity_cutoff,json=popularityCutoff,proto3" json:"popularity_cutoff,omitempty"`
	SearchMaxResults int32  `protobuf:"varint,3,opt,name=search_max_results,json=searchMaxResults,proto3" json:"search_max_results,omitempty"`
	Nsfw             bool   `protobuf:"varint,4,opt,name=nsfw,proto3" json:"nsfw,omitempty"`
}

func (x *MALConfig) Reset() {
	*x = MALConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MALConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MALConfig) ProtoMessage() {}

func (x *MALConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MALConfig.ProtoReflect.Descriptor instead.
func (*MALConfig) Descriptor() ([]byte, []int) {
	return file_api_config_proto_rawDescGZIP(), []int{1}
}

func (x *MALConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MALConfig) GetPopularityCutoff() int32 {
	if x != nil {
		return x.PopularityCutoff
	}
	return 0
}

func (x *MALConfig) GetSearchMaxResults() int32 {
	if x != nil {
		return x.SearchMaxResults
	}
	return 0
}

func (x *MALConfig) GetNsfw() bool {
	if x != nil {
		return x.Nsfw
	}
	return false
}

var File_api_config_proto protoreflect.FileDescriptor

var file_api_config_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x74, 0x72, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x1a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x2b, 0x0a, 0x03, 0x6d, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x74, 0x72, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4d,
	0x41, 0x4c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x03, 0x6d, 0x61, 0x6c, 0x22, 0x97, 0x01,
	0x0a, 0x09, 0x4d, 0x41, 0x4c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x11, 0x70, 0x6f, 0x70, 0x75,
	0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x63, 0x75, 0x74, 0x6f, 0x66, 0x66, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x10, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x43,
	0x75, 0x74, 0x6f, 0x66, 0x66, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f,
	0x6d, 0x61, 0x78, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x10, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x73, 0x66, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x6e, 0x73, 0x66, 0x77, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6e, 0x6b, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67,
	0x2f, 0x74, 0x72, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x2f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_config_proto_rawDescOnce sync.Once
	file_api_config_proto_rawDescData = file_api_config_proto_rawDesc
)

func file_api_config_proto_rawDescGZIP() []byte {
	file_api_config_proto_rawDescOnce.Do(func() {
		file_api_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_config_proto_rawDescData)
	})
	return file_api_config_proto_rawDescData
}

var file_api_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_config_proto_goTypes = []interface{}{
	(*Config)(nil),    // 0: truffle.config.Config
	(*MALConfig)(nil), // 1: truffle.config.MALConfig
}
var file_api_config_proto_depIdxs = []int32{
	1, // 0: truffle.config.Config.mal:type_name -> truffle.config.MALConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_config_proto_init() }
func file_api_config_proto_init() {
	if File_api_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MALConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_config_proto_goTypes,
		DependencyIndexes: file_api_config_proto_depIdxs,
		MessageInfos:      file_api_config_proto_msgTypes,
	}.Build()
	File_api_config_proto = out.File
	file_api_config_proto_rawDesc = nil
	file_api_config_proto_goTypes = nil
	file_api_config_proto_depIdxs = nil
}
